import json
import uuid
from typing import List, Dict, Any, Optional
from app.models.schemas import TaskStep, TaskStatus
from app.models.agent_state import AgentState
from app.services.llm import llm_service
from app.utils.logger import logger

class PlannerAgent:
    def __init__(self):
        self.llm = llm_service

    async def generate_plan(self, state: AgentState) -> List[TaskStep]:
        """
        Generate a multi-step plan using LLM, converting input into structured steps.
        """
        logger.info(f"Planner Agent generating plan for goal: {state.goal}")
        
        # Build context for the planner, including available tools and desired output format
        context = f"""
        Current Goal: {state.goal}
        Thoughts: {state.thoughts}
        Reasoning: {state.reasoning}
        Working Memory: {json.dumps(state.working_memory)}
        Critic Feedback: {state.critic_feedback}
        
        Available tools and their arguments:
        - android.tap(x: int, y: int): Tap on Android screen at coordinates (x, y).
        - android.swipe(x1: int, y1: int, x2: int, y2: int): Swipe on Android screen from (x1, y1) to (x2, y2).
        - android.type(text: str): Type the given text on the Android device.
        - android.open_app(package_name: str): Open an Android application by its package name (e.g., "com.google.android.youtube").
        - web.search(query: str): Perform a web search for the given query.
        - web.scrape(url: str): Scrape the content of a given URL.
        - file.write(filename: str, content: str): Write content to a specified file.
        - file.read(filename: str): Read content from a specified file.
        - shell.execute(command: str): Execute a shell command in a sandboxed environment.
        - http.request(method: str, url: str, headers: dict = None, data: dict = None): Perform an HTTP request.
        - memory.store(key: str, value: Any): Store a value in the agent's long-term memory.
        - memory.retrieve(key: str): Retrieve a value from the agent's long-term memory.
        
        Based on the goal and context, generate a list of structured steps to achieve the goal. Each step must be a JSON object with 'tool' (e.g., 'android.open_app') and 'args' (a dictionary of arguments for the tool). If no tool is suitable, use a 'thought' tool with a 'description' argument.
        
        Example of desired output format:
        [
            {{"tool": "android.open_app", "args": {{"package_name": "com.google.android.youtube"}}}} ,
            {{"tool": "android.type", "args": {{"text": "AI news"}}}} ,
            {{"tool": "android.tap", "args": {{"x": 500, "y": 300}}}}
        ]
        
        Goal: {state.goal}
        """

        try:
            # Use the specialized plan function from LLM service
            response = await self.llm.plan(state.goal, context=context)
            
            # Extract and parse the JSON plan from the LLM response
            start = response.find("[")
            end = response.rfind("]") + 1
            if start != -1 and end != -1:
                plan_json = json.loads(response[start:end])
                steps = []
                for step_data in plan_json:
                    # Ensure 'description' is present for TaskStep, even if generated by LLM
                    description = step_data.get("description", f"Execute {step_data.get('tool')}")
                    steps.append(TaskStep(
                        id=str(uuid.uuid4()),
                        description=description,
                        tool=step_data["tool"],
                        args=step_data["args"],
                        status=TaskStatus.PENDING
                    ))
                return steps
            else:
                logger.error(f"Failed to parse plan from LLM response: {response}")
                return []
        except Exception as e:
            logger.error(f"Error generating plan with LLM: {e}")
            return []

    async def replan(self, state: AgentState, failure_reason: str) -> List[TaskStep]:
        """
        Dynamically replan based on a failure or new information.
        """
        logger.info(f"Planner Agent replanning for goal: {state.goal} due to: {failure_reason}")
        state.critic_feedback = f"Replanning needed due to: {failure_reason}"
        return await self.generate_plan(state)

planner_agent = PlannerAgent()
